/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.faro.model.impl;

import com.liferay.osb.faro.model.FaroProjectEmailDomain;
import com.liferay.osb.faro.service.FaroProjectEmailDomainLocalServiceUtil;

/**
 * The extended model base implementation for the FaroProjectEmailDomain service. Represents a row in the &quot;OSBFaro_FaroProjectEmailDomain&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FaroProjectEmailDomainImpl}.
 * </p>
 *
 * @author Matthew Kong
 * @see FaroProjectEmailDomainImpl
 * @see FaroProjectEmailDomain
 * @generated
 */
public abstract class FaroProjectEmailDomainBaseImpl
	extends FaroProjectEmailDomainModelImpl implements FaroProjectEmailDomain {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a faro project email domain model instance should use the <code>FaroProjectEmailDomain</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			FaroProjectEmailDomainLocalServiceUtil.addFaroProjectEmailDomain(
				this);
		}
		else {
			FaroProjectEmailDomainLocalServiceUtil.updateFaroProjectEmailDomain(
				this);
		}
	}

}