/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.faro.model.impl;

import com.liferay.osb.faro.model.FaroChannel;
import com.liferay.osb.faro.service.FaroChannelLocalServiceUtil;

/**
 * The extended model base implementation for the FaroChannel service. Represents a row in the &quot;OSBFaro_FaroChannel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FaroChannelImpl}.
 * </p>
 *
 * @author Matthew Kong
 * @see FaroChannelImpl
 * @see FaroChannel
 * @generated
 */
public abstract class FaroChannelBaseImpl
	extends FaroChannelModelImpl implements FaroChannel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a faro channel model instance should use the <code>FaroChannel</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			FaroChannelLocalServiceUtil.addFaroChannel(this);
		}
		else {
			FaroChannelLocalServiceUtil.updateFaroChannel(this);
		}
	}

}