/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.faro.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the FaroProjectEmailAddressDomain service. Represents a row in the &quot;OSBFaro_FaroProjectEmailAddressDomain&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.osb.faro.model.impl.FaroProjectEmailAddressDomainModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.osb.faro.model.impl.FaroProjectEmailAddressDomainImpl</code>.
 * </p>
 *
 * @author Matthew Kong
 * @see FaroProjectEmailAddressDomain
 * @generated
 */
@ProviderType
public interface FaroProjectEmailAddressDomainModel
	extends BaseModel<FaroProjectEmailAddressDomain> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a faro project email address domain model instance should use the {@link FaroProjectEmailAddressDomain} interface instead.
	 */

	/**
	 * Returns the primary key of this faro project email address domain.
	 *
	 * @return the primary key of this faro project email address domain
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this faro project email address domain.
	 *
	 * @param primaryKey the primary key of this faro project email address domain
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the faro project email address domain ID of this faro project email address domain.
	 *
	 * @return the faro project email address domain ID of this faro project email address domain
	 */
	public long getFaroProjectEmailAddressDomainId();

	/**
	 * Sets the faro project email address domain ID of this faro project email address domain.
	 *
	 * @param faroProjectEmailAddressDomainId the faro project email address domain ID of this faro project email address domain
	 */
	public void setFaroProjectEmailAddressDomainId(
		long faroProjectEmailAddressDomainId);

	/**
	 * Returns the group ID of this faro project email address domain.
	 *
	 * @return the group ID of this faro project email address domain
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this faro project email address domain.
	 *
	 * @param groupId the group ID of this faro project email address domain
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the faro project ID of this faro project email address domain.
	 *
	 * @return the faro project ID of this faro project email address domain
	 */
	public long getFaroProjectId();

	/**
	 * Sets the faro project ID of this faro project email address domain.
	 *
	 * @param faroProjectId the faro project ID of this faro project email address domain
	 */
	public void setFaroProjectId(long faroProjectId);

	/**
	 * Returns the email address domain of this faro project email address domain.
	 *
	 * @return the email address domain of this faro project email address domain
	 */
	@AutoEscape
	public String getEmailAddressDomain();

	/**
	 * Sets the email address domain of this faro project email address domain.
	 *
	 * @param emailAddressDomain the email address domain of this faro project email address domain
	 */
	public void setEmailAddressDomain(String emailAddressDomain);

	@Override
	public FaroProjectEmailAddressDomain cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}