/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.faro.service.base;

import com.liferay.osb.faro.model.FaroProject;
import com.liferay.osb.faro.service.FaroProjectLocalService;
import com.liferay.osb.faro.service.FaroProjectLocalServiceUtil;
import com.liferay.osb.faro.service.persistence.FaroChannelFinder;
import com.liferay.osb.faro.service.persistence.FaroChannelPersistence;
import com.liferay.osb.faro.service.persistence.FaroPreferencesPersistence;
import com.liferay.osb.faro.service.persistence.FaroProjectEmailAddressDomainPersistence;
import com.liferay.osb.faro.service.persistence.FaroProjectFinder;
import com.liferay.osb.faro.service.persistence.FaroProjectPersistence;
import com.liferay.osb.faro.service.persistence.FaroUserFinder;
import com.liferay.osb.faro.service.persistence.FaroUserPersistence;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.service.persistence.GroupPersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the faro project local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.osb.faro.service.impl.FaroProjectLocalServiceImpl}.
 * </p>
 *
 * @author Matthew Kong
 * @see com.liferay.osb.faro.service.impl.FaroProjectLocalServiceImpl
 * @generated
 */
public abstract class FaroProjectLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements FaroProjectLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>FaroProjectLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>FaroProjectLocalServiceUtil</code>.
	 */

	/**
	 * Adds the faro project to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect FaroProjectLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param faroProject the faro project
	 * @return the faro project that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public FaroProject addFaroProject(FaroProject faroProject) {
		faroProject.setNew(true);

		return faroProjectPersistence.update(faroProject);
	}

	/**
	 * Creates a new faro project with the primary key. Does not add the faro project to the database.
	 *
	 * @param faroProjectId the primary key for the new faro project
	 * @return the new faro project
	 */
	@Override
	@Transactional(enabled = false)
	public FaroProject createFaroProject(long faroProjectId) {
		return faroProjectPersistence.create(faroProjectId);
	}

	/**
	 * Deletes the faro project with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect FaroProjectLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param faroProjectId the primary key of the faro project
	 * @return the faro project that was removed
	 * @throws PortalException if a faro project with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public FaroProject deleteFaroProject(long faroProjectId)
		throws PortalException {

		return faroProjectPersistence.remove(faroProjectId);
	}

	/**
	 * Deletes the faro project from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect FaroProjectLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param faroProject the faro project
	 * @return the faro project that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public FaroProject deleteFaroProject(FaroProject faroProject) {
		return faroProjectPersistence.remove(faroProject);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return faroProjectPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			FaroProject.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return faroProjectPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.osb.faro.model.impl.FaroProjectModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return faroProjectPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.osb.faro.model.impl.FaroProjectModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return faroProjectPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return faroProjectPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return faroProjectPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public FaroProject fetchFaroProject(long faroProjectId) {
		return faroProjectPersistence.fetchByPrimaryKey(faroProjectId);
	}

	/**
	 * Returns the faro project with the primary key.
	 *
	 * @param faroProjectId the primary key of the faro project
	 * @return the faro project
	 * @throws PortalException if a faro project with the primary key could not be found
	 */
	@Override
	public FaroProject getFaroProject(long faroProjectId)
		throws PortalException {

		return faroProjectPersistence.findByPrimaryKey(faroProjectId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(faroProjectLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(FaroProject.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("faroProjectId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			faroProjectLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(FaroProject.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"faroProjectId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(faroProjectLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(FaroProject.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("faroProjectId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return faroProjectPersistence.create(((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement FaroProjectLocalServiceImpl#deleteFaroProject(FaroProject) to avoid orphaned data");
		}

		return faroProjectLocalService.deleteFaroProject(
			(FaroProject)persistedModel);
	}

	@Override
	public BasePersistence<FaroProject> getBasePersistence() {
		return faroProjectPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return faroProjectPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the faro projects.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.osb.faro.model.impl.FaroProjectModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of faro projects
	 * @param end the upper bound of the range of faro projects (not inclusive)
	 * @return the range of faro projects
	 */
	@Override
	public List<FaroProject> getFaroProjects(int start, int end) {
		return faroProjectPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of faro projects.
	 *
	 * @return the number of faro projects
	 */
	@Override
	public int getFaroProjectsCount() {
		return faroProjectPersistence.countAll();
	}

	/**
	 * Updates the faro project in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect FaroProjectLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param faroProject the faro project
	 * @return the faro project that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public FaroProject updateFaroProject(FaroProject faroProject) {
		return faroProjectPersistence.update(faroProject);
	}

	/**
	 * Returns the faro project local service.
	 *
	 * @return the faro project local service
	 */
	public FaroProjectLocalService getFaroProjectLocalService() {
		return faroProjectLocalService;
	}

	/**
	 * Sets the faro project local service.
	 *
	 * @param faroProjectLocalService the faro project local service
	 */
	public void setFaroProjectLocalService(
		FaroProjectLocalService faroProjectLocalService) {

		this.faroProjectLocalService = faroProjectLocalService;
	}

	/**
	 * Returns the faro project persistence.
	 *
	 * @return the faro project persistence
	 */
	public FaroProjectPersistence getFaroProjectPersistence() {
		return faroProjectPersistence;
	}

	/**
	 * Sets the faro project persistence.
	 *
	 * @param faroProjectPersistence the faro project persistence
	 */
	public void setFaroProjectPersistence(
		FaroProjectPersistence faroProjectPersistence) {

		this.faroProjectPersistence = faroProjectPersistence;
	}

	/**
	 * Returns the faro project finder.
	 *
	 * @return the faro project finder
	 */
	public FaroProjectFinder getFaroProjectFinder() {
		return faroProjectFinder;
	}

	/**
	 * Sets the faro project finder.
	 *
	 * @param faroProjectFinder the faro project finder
	 */
	public void setFaroProjectFinder(FaroProjectFinder faroProjectFinder) {
		this.faroProjectFinder = faroProjectFinder;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the faro channel local service.
	 *
	 * @return the faro channel local service
	 */
	public com.liferay.osb.faro.service.FaroChannelLocalService
		getFaroChannelLocalService() {

		return faroChannelLocalService;
	}

	/**
	 * Sets the faro channel local service.
	 *
	 * @param faroChannelLocalService the faro channel local service
	 */
	public void setFaroChannelLocalService(
		com.liferay.osb.faro.service.FaroChannelLocalService
			faroChannelLocalService) {

		this.faroChannelLocalService = faroChannelLocalService;
	}

	/**
	 * Returns the faro channel persistence.
	 *
	 * @return the faro channel persistence
	 */
	public FaroChannelPersistence getFaroChannelPersistence() {
		return faroChannelPersistence;
	}

	/**
	 * Sets the faro channel persistence.
	 *
	 * @param faroChannelPersistence the faro channel persistence
	 */
	public void setFaroChannelPersistence(
		FaroChannelPersistence faroChannelPersistence) {

		this.faroChannelPersistence = faroChannelPersistence;
	}

	/**
	 * Returns the faro channel finder.
	 *
	 * @return the faro channel finder
	 */
	public FaroChannelFinder getFaroChannelFinder() {
		return faroChannelFinder;
	}

	/**
	 * Sets the faro channel finder.
	 *
	 * @param faroChannelFinder the faro channel finder
	 */
	public void setFaroChannelFinder(FaroChannelFinder faroChannelFinder) {
		this.faroChannelFinder = faroChannelFinder;
	}

	/**
	 * Returns the faro preferences local service.
	 *
	 * @return the faro preferences local service
	 */
	public com.liferay.osb.faro.service.FaroPreferencesLocalService
		getFaroPreferencesLocalService() {

		return faroPreferencesLocalService;
	}

	/**
	 * Sets the faro preferences local service.
	 *
	 * @param faroPreferencesLocalService the faro preferences local service
	 */
	public void setFaroPreferencesLocalService(
		com.liferay.osb.faro.service.FaroPreferencesLocalService
			faroPreferencesLocalService) {

		this.faroPreferencesLocalService = faroPreferencesLocalService;
	}

	/**
	 * Returns the faro preferences persistence.
	 *
	 * @return the faro preferences persistence
	 */
	public FaroPreferencesPersistence getFaroPreferencesPersistence() {
		return faroPreferencesPersistence;
	}

	/**
	 * Sets the faro preferences persistence.
	 *
	 * @param faroPreferencesPersistence the faro preferences persistence
	 */
	public void setFaroPreferencesPersistence(
		FaroPreferencesPersistence faroPreferencesPersistence) {

		this.faroPreferencesPersistence = faroPreferencesPersistence;
	}

	/**
	 * Returns the group local service.
	 *
	 * @return the group local service
	 */
	public com.liferay.portal.kernel.service.GroupLocalService
		getGroupLocalService() {

		return groupLocalService;
	}

	/**
	 * Sets the group local service.
	 *
	 * @param groupLocalService the group local service
	 */
	public void setGroupLocalService(
		com.liferay.portal.kernel.service.GroupLocalService groupLocalService) {

		this.groupLocalService = groupLocalService;
	}

	/**
	 * Returns the group persistence.
	 *
	 * @return the group persistence
	 */
	public GroupPersistence getGroupPersistence() {
		return groupPersistence;
	}

	/**
	 * Sets the group persistence.
	 *
	 * @param groupPersistence the group persistence
	 */
	public void setGroupPersistence(GroupPersistence groupPersistence) {
		this.groupPersistence = groupPersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService
		getUserLocalService() {

		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {

		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	/**
	 * Returns the faro project email address domain local service.
	 *
	 * @return the faro project email address domain local service
	 */
	public
		com.liferay.osb.faro.service.FaroProjectEmailAddressDomainLocalService
			getFaroProjectEmailAddressDomainLocalService() {

		return faroProjectEmailAddressDomainLocalService;
	}

	/**
	 * Sets the faro project email address domain local service.
	 *
	 * @param faroProjectEmailAddressDomainLocalService the faro project email address domain local service
	 */
	public void setFaroProjectEmailAddressDomainLocalService(
		com.liferay.osb.faro.service.FaroProjectEmailAddressDomainLocalService
			faroProjectEmailAddressDomainLocalService) {

		this.faroProjectEmailAddressDomainLocalService =
			faroProjectEmailAddressDomainLocalService;
	}

	/**
	 * Returns the faro project email address domain persistence.
	 *
	 * @return the faro project email address domain persistence
	 */
	public FaroProjectEmailAddressDomainPersistence
		getFaroProjectEmailAddressDomainPersistence() {

		return faroProjectEmailAddressDomainPersistence;
	}

	/**
	 * Sets the faro project email address domain persistence.
	 *
	 * @param faroProjectEmailAddressDomainPersistence the faro project email address domain persistence
	 */
	public void setFaroProjectEmailAddressDomainPersistence(
		FaroProjectEmailAddressDomainPersistence
			faroProjectEmailAddressDomainPersistence) {

		this.faroProjectEmailAddressDomainPersistence =
			faroProjectEmailAddressDomainPersistence;
	}

	/**
	 * Returns the faro user local service.
	 *
	 * @return the faro user local service
	 */
	public com.liferay.osb.faro.service.FaroUserLocalService
		getFaroUserLocalService() {

		return faroUserLocalService;
	}

	/**
	 * Sets the faro user local service.
	 *
	 * @param faroUserLocalService the faro user local service
	 */
	public void setFaroUserLocalService(
		com.liferay.osb.faro.service.FaroUserLocalService
			faroUserLocalService) {

		this.faroUserLocalService = faroUserLocalService;
	}

	/**
	 * Returns the faro user persistence.
	 *
	 * @return the faro user persistence
	 */
	public FaroUserPersistence getFaroUserPersistence() {
		return faroUserPersistence;
	}

	/**
	 * Sets the faro user persistence.
	 *
	 * @param faroUserPersistence the faro user persistence
	 */
	public void setFaroUserPersistence(
		FaroUserPersistence faroUserPersistence) {

		this.faroUserPersistence = faroUserPersistence;
	}

	/**
	 * Returns the faro user finder.
	 *
	 * @return the faro user finder
	 */
	public FaroUserFinder getFaroUserFinder() {
		return faroUserFinder;
	}

	/**
	 * Sets the faro user finder.
	 *
	 * @param faroUserFinder the faro user finder
	 */
	public void setFaroUserFinder(FaroUserFinder faroUserFinder) {
		this.faroUserFinder = faroUserFinder;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register(
			"com.liferay.osb.faro.model.FaroProject", faroProjectLocalService);

		_setLocalServiceUtilService(faroProjectLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.liferay.osb.faro.model.FaroProject");

		_setLocalServiceUtilService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return FaroProjectLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return FaroProject.class;
	}

	protected String getModelClassName() {
		return FaroProject.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = faroProjectPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		FaroProjectLocalService faroProjectLocalService) {

		try {
			Field field = FaroProjectLocalServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, faroProjectLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@BeanReference(type = FaroProjectLocalService.class)
	protected FaroProjectLocalService faroProjectLocalService;

	@BeanReference(type = FaroProjectPersistence.class)
	protected FaroProjectPersistence faroProjectPersistence;

	@BeanReference(type = FaroProjectFinder.class)
	protected FaroProjectFinder faroProjectFinder;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@BeanReference(
		type = com.liferay.osb.faro.service.FaroChannelLocalService.class
	)
	protected com.liferay.osb.faro.service.FaroChannelLocalService
		faroChannelLocalService;

	@BeanReference(type = FaroChannelPersistence.class)
	protected FaroChannelPersistence faroChannelPersistence;

	@BeanReference(type = FaroChannelFinder.class)
	protected FaroChannelFinder faroChannelFinder;

	@BeanReference(
		type = com.liferay.osb.faro.service.FaroPreferencesLocalService.class
	)
	protected com.liferay.osb.faro.service.FaroPreferencesLocalService
		faroPreferencesLocalService;

	@BeanReference(type = FaroPreferencesPersistence.class)
	protected FaroPreferencesPersistence faroPreferencesPersistence;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.GroupLocalService.class
	)
	protected com.liferay.portal.kernel.service.GroupLocalService
		groupLocalService;

	@ServiceReference(type = GroupPersistence.class)
	protected GroupPersistence groupPersistence;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.UserLocalService.class
	)
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;

	@BeanReference(
		type = com.liferay.osb.faro.service.FaroProjectEmailAddressDomainLocalService.class
	)
	protected
		com.liferay.osb.faro.service.FaroProjectEmailAddressDomainLocalService
			faroProjectEmailAddressDomainLocalService;

	@BeanReference(type = FaroProjectEmailAddressDomainPersistence.class)
	protected FaroProjectEmailAddressDomainPersistence
		faroProjectEmailAddressDomainPersistence;

	@BeanReference(
		type = com.liferay.osb.faro.service.FaroUserLocalService.class
	)
	protected com.liferay.osb.faro.service.FaroUserLocalService
		faroUserLocalService;

	@BeanReference(type = FaroUserPersistence.class)
	protected FaroUserPersistence faroUserPersistence;

	@BeanReference(type = FaroUserFinder.class)
	protected FaroUserFinder faroUserFinder;

	private static final Log _log = LogFactoryUtil.getLog(
		FaroProjectLocalServiceBaseImpl.class);

	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry
		persistedModelLocalServiceRegistry;

}