/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.faro.contacts.model.impl;

import com.liferay.osb.faro.contacts.model.ContactsCardTemplate;
import com.liferay.osb.faro.contacts.service.ContactsCardTemplateLocalServiceUtil;

/**
 * The extended model base implementation for the ContactsCardTemplate service. Represents a row in the &quot;OSBFaro_ContactsCardTemplate&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ContactsCardTemplateImpl}.
 * </p>
 *
 * @author Shinn Lok
 * @see ContactsCardTemplateImpl
 * @see ContactsCardTemplate
 * @generated
 */
public abstract class ContactsCardTemplateBaseImpl
	extends ContactsCardTemplateModelImpl implements ContactsCardTemplate {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a contacts card template model instance should use the <code>ContactsCardTemplate</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ContactsCardTemplateLocalServiceUtil.addContactsCardTemplate(this);
		}
		else {
			ContactsCardTemplateLocalServiceUtil.updateContactsCardTemplate(
				this);
		}
	}

}